language: java
jdk: openjdk8

services:
  - docker

before_script:
  - docker run -p 9042:9042 --rm --name mycassandra -d cassandra
  - docker exec mycassandra bash -l -c "cqlsh -e \"CREATE KEYSPACE betterbotz WITH REPLICATION = {'class': 'SimpleStrategy', 'replication_factor': 1};\""
