language: java
jdk: openjdk8

services:
  - docker

before_script:
  - docker run -p 9042:9042 --rm --name mycassandra --network mycassandranetwork -d cassandra
  - docker run -it --network mycassandranetwork --rm cassandra cqlsh -f r2.cql mycassandra