name: Build, Test, and Prepare Release Candidate

on:
  pull_request:
    types:
      - labeled
      - reopened
      - synchronize

jobs:
  integration-tests:
    name: Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, 'Extension Release Candidate :rocket:' )
    strategy:
      matrix:
        java: [8, 11]
    steps:
    - uses: actions/checkout@v2
    - name: Cache Local Maven Repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'

    - name: Start Cassandra Container
      run: docker run -p 9042:9042 -v $(pwd):/app --name mycassandra -d cassandra

    - name: Wait for cassandra to start up
      run: sleep 90s

    - name: Check cassandra status
      run: docker ps -a

    - name: Check cassandra logs
      run: docker logs mycassandra

    - name: Load Cassandra Config
      run: docker exec mycassandra cqlsh localhost 9042 -f /app/test.cql

    - name: Test With Maven
      run: mvn clean verify
